const NAME_DB_PROVIDER="DATA_SOURCE";
const NAME_PRODUCT_REPOSITORY="PRODUCT_REPOSITORY";
const NAME_CATEGORY_REPOSITORY="CATEGORY_REPOSITORY";
const NAME_BRAND_REPOSITORY="BRAND_REPOSITORY";

export {
    NAME_DB_PROVIDER,
    NAME_PRODUCT_REPOSITORY,
    NAME_CATEGORY_REPOSITORY,
    NAME_BRAND_REPOSITORY,
}
